/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paul;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.io.File;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

import static java.lang.System.out;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author paulk
 */
public class InterfaceDesign extends javax.swing.JFrame {

    Logic game = new Logic(); //object of logic class that will be used throughout game
    int rows = 1;
    User newUser = new User();

    Connect db = new Connect();
    int result;
 boolean skip = true;
    /**
     * Creates new form InterfaceDesign
     */
    public InterfaceDesign() {
        initComponents();

        this.setLocationRelativeTo(null); //centers the frame relative to screen
        frmUserPage.setLocationRelativeTo(null);

        frmUserPage.setVisible(false);
        btnEnterWord.setEnabled(false);// "GO!" button should not allow for empty string to pass
        btnEnterUserInfo.setEnabled(false);

        frmUserPage.getContentPane().setBackground(new Color(102, 0, 102)); //set background colour

        frmLogin.setVisible(true);
        frmLogin.setLocationRelativeTo(null);
        frmLogin.getContentPane().setBackground(new Color(158, 192, 247));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        frmUserPage = new javax.swing.JFrame();
        btnPlay = new javax.swing.JButton();
        lblUserInformation = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaInfoArea = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        pnlLeaderboard = new javax.swing.JPanel();
        lblLeaderboard = new javax.swing.JLabel();
        lblFirst = new javax.swing.JLabel();
        lblSecond = new javax.swing.JLabel();
        lblThird = new javax.swing.JLabel();
        lblFourth = new javax.swing.JLabel();
        lblFifth = new javax.swing.JLabel();
        btnBackToLogin = new javax.swing.JButton();
        btnRules = new javax.swing.JButton();
        frmLogin = new javax.swing.JFrame();
        btnEnterUserInfo = new javax.swing.JButton();
        lblBanner = new javax.swing.JLabel();
        radLogin = new javax.swing.JRadioButton();
        radSignup = new javax.swing.JRadioButton();
        lblUsername = new javax.swing.JLabel();
        txfUsername = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        passPassword = new javax.swing.JPasswordField();
        btnGuest = new javax.swing.JButton();
        rgpAccount = new javax.swing.ButtonGroup();
        pnlBackground = new javax.swing.JPanel();
        lpaneBackground = new javax.swing.JLayeredPane();
        txfWordField = new javax.swing.JTextField();
        scrllPanelDiscardment = new javax.swing.JScrollPane();
        txaDiscardedLetters = new javax.swing.JTextArea();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        btnRow1Num3 = new javax.swing.JButton();
        btnRow4Num2 = new javax.swing.JButton();
        btnRow3Num4 = new javax.swing.JButton();
        btnRow4Num4 = new javax.swing.JButton();
        btnRow1Num4 = new javax.swing.JButton();
        btnRow2Num3 = new javax.swing.JButton();
        btnRow5Num2 = new javax.swing.JButton();
        btnRow3Num3 = new javax.swing.JButton();
        btnRow2Num4 = new javax.swing.JButton();
        btnRow2Num2 = new javax.swing.JButton();
        btnRow4Num3 = new javax.swing.JButton();
        btnRow4Num1 = new javax.swing.JButton();
        btnRow3Num2 = new javax.swing.JButton();
        btnRow5Num3 = new javax.swing.JButton();
        btnRow1Num1 = new javax.swing.JButton();
        btnRow1Num2 = new javax.swing.JButton();
        btnRow2Num1 = new javax.swing.JButton();
        btnRow5Num1 = new javax.swing.JButton();
        btnRow3Num1 = new javax.swing.JButton();
        btnRow5Num4 = new javax.swing.JButton();
        btnEnterWord = new javax.swing.JButton();
        lblDiscardedLetters = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        frmUserPage.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        frmUserPage.setTitle("User Page");
        frmUserPage.setBackground(new java.awt.Color(102, 0, 102));
        frmUserPage.setMinimumSize(new java.awt.Dimension(650, 666));
        frmUserPage.setName("User's Information Page"); // NOI18N
        frmUserPage.setResizable(false);
        frmUserPage.setSize(new java.awt.Dimension(650, 666));

        btnPlay.setBackground(new java.awt.Color(255, 204, 255));
        btnPlay.setFont(new java.awt.Font("Stencil", 0, 32)); // NOI18N
        btnPlay.setForeground(new java.awt.Color(204, 0, 51));
        btnPlay.setText("PLAY");
        btnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayActionPerformed(evt);
            }
        });

        lblUserInformation.setBackground(new java.awt.Color(204, 204, 255));
        lblUserInformation.setFont(new java.awt.Font("Showcard Gothic", 1, 26)); // NOI18N
        lblUserInformation.setForeground(new java.awt.Color(204, 204, 255));
        lblUserInformation.setText("User Information:");

        txaInfoArea.setColumns(20);
        txaInfoArea.setRows(5);
        jScrollPane1.setViewportView(txaInfoArea);

        pnlLeaderboard.setBackground(new java.awt.Color(162, 243, 177));
        pnlLeaderboard.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(153, 153, 0)));

        lblLeaderboard.setFont(new java.awt.Font("Segoe Script", 1, 26)); // NOI18N
        lblLeaderboard.setText("<html>\n<b><u>\nLeaderboard:");

        lblFirst.setText("1. ");

        lblSecond.setText("2. ");

        lblThird.setText("3. ");

        lblFourth.setText("4. ");

        lblFifth.setText("5.");

        javax.swing.GroupLayout pnlLeaderboardLayout = new javax.swing.GroupLayout(pnlLeaderboard);
        pnlLeaderboard.setLayout(pnlLeaderboardLayout);
        pnlLeaderboardLayout.setHorizontalGroup(
            pnlLeaderboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLeaderboardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLeaderboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLeaderboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLeaderboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFirst, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSecond, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblThird, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFourth, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFifth, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlLeaderboardLayout.setVerticalGroup(
            pnlLeaderboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLeaderboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLeaderboard, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFirst)
                .addGap(18, 18, 18)
                .addComponent(lblSecond)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblThird)
                .addGap(18, 18, 18)
                .addComponent(lblFourth)
                .addGap(18, 18, 18)
                .addComponent(lblFifth)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        btnBackToLogin.setBackground(new java.awt.Color(255, 102, 102));
        btnBackToLogin.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnBackToLogin.setText("BACK");
        btnBackToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToLoginActionPerformed(evt);
            }
        });

        btnRules.setBackground(new java.awt.Color(255, 255, 153));
        btnRules.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        btnRules.setText("HOW TO PLAY");
        btnRules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRulesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frmUserPageLayout = new javax.swing.GroupLayout(frmUserPage.getContentPane());
        frmUserPage.getContentPane().setLayout(frmUserPageLayout);
        frmUserPageLayout.setHorizontalGroup(
            frmUserPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(frmUserPageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(frmUserPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(pnlLeaderboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(frmUserPageLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(frmUserPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(frmUserPageLayout.createSequentialGroup()
                        .addComponent(btnBackToLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRules, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        frmUserPageLayout.setVerticalGroup(
            frmUserPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frmUserPageLayout.createSequentialGroup()
                .addGroup(frmUserPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(frmUserPageLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lblUserInformation, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(frmUserPageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlLeaderboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(frmUserPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRules, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                    .addComponent(btnBackToLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        frmLogin.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        frmLogin.setTitle("Login/Sign Up");
        frmLogin.setMinimumSize(new java.awt.Dimension(650, 666));
        frmLogin.setSize(new java.awt.Dimension(650, 666));

        btnEnterUserInfo.setBackground(new java.awt.Color(0, 97, 56));
        btnEnterUserInfo.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        btnEnterUserInfo.setForeground(new java.awt.Color(255, 164, 212));
        btnEnterUserInfo.setText("ENTER");
        btnEnterUserInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterUserInfoActionPerformed(evt);
            }
        });

        lblBanner.setBackground(new java.awt.Color(153, 153, 255));
        lblBanner.setFont(new java.awt.Font("Vladimir Script", 1, 60)); // NOI18N
        lblBanner.setForeground(new java.awt.Color(0, 102, 102));
        lblBanner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBanner.setText("Super Simple Wordle");
        lblBanner.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblBanner.setOpaque(true);

        rgpAccount.add(radLogin);
        radLogin.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 20)); // NOI18N
        radLogin.setText("Login (existing accounts)");
        radLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radLoginActionPerformed(evt);
            }
        });

        rgpAccount.add(radSignup);
        radSignup.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 20)); // NOI18N
        radSignup.setText("Sign Up (new comers)");
        radSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radSignupActionPerformed(evt);
            }
        });

        lblUsername.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        lblUsername.setText("Username:");

        txfUsername.setBackground(new java.awt.Color(255, 211, 126));
        txfUsername.setFont(new java.awt.Font("Viner Hand ITC", 3, 18)); // NOI18N
        txfUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txfUsernameKeyTyped(evt);
            }
        });

        lblPassword.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        lblPassword.setText("Password:");

        passPassword.setBackground(new java.awt.Color(255, 211, 126));
        passPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passPasswordKeyTyped(evt);
            }
        });

        btnGuest.setText("guest");
        btnGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout frmLoginLayout = new javax.swing.GroupLayout(frmLogin.getContentPane());
        frmLogin.getContentPane().setLayout(frmLoginLayout);
        frmLoginLayout.setHorizontalGroup(
            frmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frmLoginLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(frmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(frmLoginLayout.createSequentialGroup()
                        .addGroup(frmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEnterUserInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(frmLoginLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(lblBanner, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29))
                    .addGroup(frmLoginLayout.createSequentialGroup()
                        .addComponent(radLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radSignup)
                        .addGap(93, 93, 93))))
            .addGroup(frmLoginLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(frmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGuest)
                    .addGroup(frmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblPassword)
                        .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txfUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                        .addComponent(passPassword)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        frmLoginLayout.setVerticalGroup(
            frmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, frmLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBanner, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(frmLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radLogin)
                    .addComponent(radSignup))
                .addGap(34, 34, 34)
                .addComponent(lblUsername)
                .addGap(26, 26, 26)
                .addComponent(txfUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(lblPassword)
                .addGap(18, 18, 18)
                .addComponent(passPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btnGuest)
                .addGap(27, 27, 27)
                .addComponent(btnEnterUserInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 0, 102));
        setForeground(new java.awt.Color(102, 0, 102));
        setMinimumSize(new java.awt.Dimension(650, 666));
        setName("gameFrame"); // NOI18N
        setResizable(false);
        setSize(new java.awt.Dimension(650, 666));

        txfWordField.setFont(new java.awt.Font("Tempus Sans ITC", 1, 30)); // NOI18N
        txfWordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfWordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txfWordFieldKeyTyped(evt);
            }
        });
        lpaneBackground.add(txfWordField);
        txfWordField.setBounds(40, 390, 373, 46);

        scrllPanelDiscardment.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrllPanelDiscardment.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txaDiscardedLetters.setBackground(new java.awt.Color(204, 204, 255));
        txaDiscardedLetters.setColumns(5);
        txaDiscardedLetters.setFont(new java.awt.Font("Monospaced", 3, 30)); // NOI18N
        txaDiscardedLetters.setLineWrap(true);
        txaDiscardedLetters.setRows(5);
        txaDiscardedLetters.setWrapStyleWord(true);
        txaDiscardedLetters.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txaDiscardedLetters.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txaDiscardedLetters.setDisabledTextColor(new java.awt.Color(153, 0, 0));
        txaDiscardedLetters.setEnabled(false);
        txaDiscardedLetters.setMinimumSize(new java.awt.Dimension(570, 118));
        scrllPanelDiscardment.setViewportView(txaDiscardedLetters);

        lpaneBackground.add(scrllPanelDiscardment);
        scrllPanelDiscardment.setBounds(90, 530, 460, 97);

        btnRow1Num3.setBackground(new java.awt.Color(255, 204, 255));
        btnRow1Num3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        btnRow4Num2.setBackground(new java.awt.Color(255, 204, 255));
        btnRow4Num2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        btnRow3Num4.setBackground(new java.awt.Color(255, 204, 255));
        btnRow3Num4.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        btnRow4Num4.setBackground(new java.awt.Color(255, 204, 255));
        btnRow4Num4.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        btnRow1Num4.setBackground(new java.awt.Color(255, 204, 255));
        btnRow1Num4.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        btnRow2Num3.setBackground(new java.awt.Color(255, 204, 255));
        btnRow2Num3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        btnRow5Num2.setBackground(new java.awt.Color(255, 204, 255));
        btnRow5Num2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        btnRow3Num3.setBackground(new java.awt.Color(255, 204, 255));
        btnRow3Num3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        btnRow2Num4.setBackground(new java.awt.Color(255, 204, 255));
        btnRow2Num4.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        btnRow2Num2.setBackground(new java.awt.Color(255, 204, 255));
        btnRow2Num2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        btnRow4Num3.setBackground(new java.awt.Color(255, 204, 255));
        btnRow4Num3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        btnRow4Num1.setBackground(new java.awt.Color(255, 204, 255));
        btnRow4Num1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        btnRow3Num2.setBackground(new java.awt.Color(255, 204, 255));
        btnRow3Num2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        btnRow5Num3.setBackground(new java.awt.Color(255, 204, 255));
        btnRow5Num3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        btnRow1Num1.setBackground(new java.awt.Color(255, 204, 255));
        btnRow1Num1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        btnRow1Num2.setBackground(new java.awt.Color(255, 204, 255));
        btnRow1Num2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        btnRow2Num1.setBackground(new java.awt.Color(255, 204, 255));
        btnRow2Num1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        btnRow5Num1.setBackground(new java.awt.Color(255, 204, 255));
        btnRow5Num1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        btnRow3Num1.setBackground(new java.awt.Color(255, 204, 255));
        btnRow3Num1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        btnRow5Num4.setBackground(new java.awt.Color(255, 204, 255));
        btnRow5Num4.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        jLayeredPane1.setLayer(btnRow1Num3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnRow4Num2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnRow3Num4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnRow4Num4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnRow1Num4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnRow2Num3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnRow5Num2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnRow3Num3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnRow2Num4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnRow2Num2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnRow4Num3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnRow4Num1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnRow3Num2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnRow5Num3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnRow1Num1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnRow1Num2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnRow2Num1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnRow5Num1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnRow3Num1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnRow5Num4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRow4Num1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRow3Num1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRow5Num1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRow2Num1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRow1Num1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRow4Num2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRow3Num2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRow5Num2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRow2Num2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRow1Num2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRow4Num3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRow3Num3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRow5Num3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRow2Num3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRow1Num3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRow4Num4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRow3Num4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRow5Num4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRow1Num4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRow2Num4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLayeredPane1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnRow1Num1, btnRow1Num2, btnRow1Num3, btnRow1Num4, btnRow2Num1, btnRow2Num2, btnRow2Num3, btnRow2Num4, btnRow3Num1, btnRow3Num2, btnRow3Num3, btnRow3Num4, btnRow4Num1, btnRow4Num2, btnRow4Num3, btnRow4Num4, btnRow5Num1, btnRow5Num2, btnRow5Num3, btnRow5Num4});

        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRow1Num3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRow1Num2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRow1Num1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRow1Num4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRow2Num4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRow2Num3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRow2Num2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRow2Num1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRow3Num4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRow3Num3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRow3Num2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRow3Num1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRow4Num4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRow4Num3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRow4Num2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRow4Num1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRow5Num4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRow5Num3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRow5Num2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRow5Num1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jLayeredPane1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnRow1Num1, btnRow1Num2, btnRow1Num3, btnRow1Num4, btnRow2Num1, btnRow2Num2, btnRow2Num3, btnRow2Num4, btnRow3Num1, btnRow3Num2, btnRow3Num3, btnRow3Num4, btnRow4Num1, btnRow4Num2, btnRow4Num3, btnRow4Num4, btnRow5Num1, btnRow5Num2, btnRow5Num3, btnRow5Num4});

        lpaneBackground.add(jLayeredPane1);
        jLayeredPane1.setBounds(150, 20, 315, 344);

        btnEnterWord.setFont(new java.awt.Font("Tahoma", 2, 28)); // NOI18N
        btnEnterWord.setText("GO!");
        btnEnterWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterWordActionPerformed(evt);
            }
        });
        btnEnterWord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnEnterWordKeyPressed(evt);
            }
        });
        lpaneBackground.add(btnEnterWord);
        btnEnterWord.setBounds(440, 390, 136, 46);

        lblDiscardedLetters.setFont(new java.awt.Font("Times New Roman", 1, 25)); // NOI18N
        lblDiscardedLetters.setForeground(new java.awt.Color(204, 255, 255));
        lblDiscardedLetters.setText("Discardments:");
        lpaneBackground.add(lblDiscardedLetters);
        lblDiscardedLetters.setBounds(80, 480, 157, 29);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blue_background.jpg"))); // NOI18N
        lpaneBackground.add(lblBackground);
        lblBackground.setBounds(0, -10, 627, 640);

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lpaneBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addComponent(lpaneBackground, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
        );

        jMenu1.setText("Help");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItem1.setText("Rules");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txfWordFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfWordFieldKeyTyped
        // TODO add your handling code here:
        btnEnterWord.setEnabled(true);
    }//GEN-LAST:event_txfWordFieldKeyTyped

    private void btnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayActionPerformed
        // mystery word is set when player presses "play"
txaDiscardedLetters.setText("");
        game.setMysteryWord();
        System.out.println(game.getMysteryWord());

        frmUserPage.setVisible(false);
        this.setVisible(true);
        
       
        
        btnRow1Num1.setText("");
        btnRow1Num2.setText("");
        btnRow1Num3.setText("");
        btnRow1Num4.setText("");
        
        btnRow2Num1.setText("");
        btnRow2Num2.setText("");
        btnRow2Num3.setText("");
        btnRow2Num4.setText("");
        
        btnRow3Num1.setText("");
        btnRow3Num2.setText("");
        btnRow3Num3.setText("");
        btnRow3Num4.setText("");
        
        btnRow4Num1.setText("");
        btnRow4Num2.setText("");
        btnRow4Num3.setText("");
        btnRow4Num4.setText("");
        
        btnRow5Num1.setText("");
        btnRow5Num2.setText("");
        btnRow5Num3.setText("");
        btnRow5Num4.setText("");
        
        
        //Copied and pasted code from initComponents
        btnRow1Num3.setBackground(new java.awt.Color(255, 204, 255));
        btnRow1Num3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        btnRow4Num2.setBackground(new java.awt.Color(255, 204, 255));
        btnRow4Num2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        btnRow3Num4.setBackground(new java.awt.Color(255, 204, 255));
        btnRow3Num4.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        btnRow4Num4.setBackground(new java.awt.Color(255, 204, 255));
        btnRow4Num4.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        btnRow1Num4.setBackground(new java.awt.Color(255, 204, 255));
        btnRow1Num4.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        btnRow2Num3.setBackground(new java.awt.Color(255, 204, 255));
        btnRow2Num3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        btnRow5Num2.setBackground(new java.awt.Color(255, 204, 255));
        btnRow5Num2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        btnRow3Num3.setBackground(new java.awt.Color(255, 204, 255));
        btnRow3Num3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        btnRow2Num4.setBackground(new java.awt.Color(255, 204, 255));
        btnRow2Num4.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        btnRow2Num2.setBackground(new java.awt.Color(255, 204, 255));
        btnRow2Num2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        btnRow4Num3.setBackground(new java.awt.Color(255, 204, 255));
        btnRow4Num3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        btnRow4Num1.setBackground(new java.awt.Color(255, 204, 255));
        btnRow4Num1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        btnRow3Num2.setBackground(new java.awt.Color(255, 204, 255));
        btnRow3Num2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        btnRow5Num3.setBackground(new java.awt.Color(255, 204, 255));
        btnRow5Num3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        btnRow1Num1.setBackground(new java.awt.Color(255, 204, 255));
        btnRow1Num1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        btnRow1Num2.setBackground(new java.awt.Color(255, 204, 255));
        btnRow1Num2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        btnRow2Num1.setBackground(new java.awt.Color(255, 204, 255));
        btnRow2Num1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        btnRow5Num1.setBackground(new java.awt.Color(255, 204, 255));
        btnRow5Num1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        btnRow3Num1.setBackground(new java.awt.Color(255, 204, 255));
        btnRow3Num1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N

        btnRow5Num4.setBackground(new java.awt.Color(255, 204, 255));
        btnRow5Num4.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
                
    }//GEN-LAST:event_btnPlayActionPerformed

    private void btnEnterWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterWordActionPerformed
        goButton();

    }//GEN-LAST:event_btnEnterWordActionPerformed
    public void setlbls(String one, String two, String three, String four, String five) {
        lblFirst.setText("1. " + one);
        lblSecond.setText("2. " + two);
        lblThird.setText("3. " + three);
        lblFourth.setText("4. " + four);
        lblFifth.setText("5. " + five);
    }
    private void btnEnterWordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnEnterWordKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) { //if enter button is pressed
            goButton();
        }
    }//GEN-LAST:event_btnEnterWordKeyPressed

    private void btnEnterUserInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterUserInfoActionPerformed
        enterButton();

    }//GEN-LAST:event_btnEnterUserInfoActionPerformed

    private void txfUsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txfUsernameKeyTyped
        btnEnterUserInfo.setEnabled(true);
    }//GEN-LAST:event_txfUsernameKeyTyped

    private void passPasswordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passPasswordKeyTyped
        btnEnterUserInfo.setEnabled(true);
    }//GEN-LAST:event_passPasswordKeyTyped

    private void radLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radLoginActionPerformed
        btnEnterUserInfo.setEnabled(true);
    }//GEN-LAST:event_radLoginActionPerformed

    private void radSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radSignupActionPerformed
        btnEnterUserInfo.setEnabled(true);
    }//GEN-LAST:event_radSignupActionPerformed

    private void btnBackToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToLoginActionPerformed
       frmLogin.setVisible(true);
       frmUserPage.setVisible(false);
    }//GEN-LAST:event_btnBackToLoginActionPerformed

    private void btnRulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRulesActionPerformed
        JOptionPane.showMessageDialog(this, " How to Play:\n" +
"Wordle is a game in which the player attempts to guess a word within a limited amount of tries\n"
                + " (eg. Guessing a  4 letter word in 5 tries). The letters which are guessed in the correct place \n"
                + "will be highlighted as green and the letters which occur in the mystery word but are\n"
                + " not guessed in the correct place will be highlighted as gold.", "RULES", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnRulesActionPerformed

    private void btnGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuestActionPerformed
        frmUserPage.setVisible(true);
        frmLogin.setVisible(false);
        
        skip = false; //skip setting scores
    }//GEN-LAST:event_btnGuestActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
          JOptionPane.showMessageDialog(this, " How to Play:\n" +
"Wordle is a game in which the player attempts to guess a word within a limited amount of tries\n"
                + " (eg. Guessing a  4 letter word in 5 tries). The letters which are guessed in the correct place \n"
                + "will be highlighted as green and the letters which occur in the mystery word but are\n"
                + " not guessed in the correct place will be highlighted as gold.", "RULES", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    public void goButton() {
        String typedWord = txfWordField.getText().toLowerCase();
        typedWord.trim(); //remove whitespace from both ends of string

        if ((typedWord.length() == 4) && (!typedWord.contains(" "))) { // if input is valid
            //The following checks the letters in the guessed word against
            //the letters in the mystery word, color coding them/
            Color correct = new Color(116, 161, 128);
            Color inWord = new Color(237, 202, 88);
            switch (rows) {
                case 1:
                    btnRow1Num1.setText("" + typedWord.charAt(0));
                    if (game.checkLetterInWord(typedWord.charAt(0))) {
                        btnRow1Num1.setBackground(inWord);
                        if (game.checkLetterInPosition(typedWord.charAt(0), game.getMysteryWord().charAt(0))) {
                            btnRow1Num1.setBackground(correct);
                        }
                    } else {
                        if (!txaDiscardedLetters.getText().contains("" + typedWord.charAt(0))) {
                            txaDiscardedLetters.append(typedWord.charAt(0) + " ");
                        }
                    }
                    btnRow1Num2.setText("" + typedWord.charAt(1));
                    if (game.checkLetterInWord(typedWord.charAt(1))) {
                        btnRow1Num2.setBackground(inWord);
                        if (game.checkLetterInPosition(typedWord.charAt(1), game.getMysteryWord().charAt(1))) {
                            btnRow1Num2.setBackground(correct);
                        }
                    } else {
                        if (!txaDiscardedLetters.getText().contains("" + typedWord.charAt(1))) {
                            txaDiscardedLetters.append(typedWord.charAt(1) + " ");
                        }
                    }
                    btnRow1Num3.setText("" + typedWord.charAt(2));
                    if (game.checkLetterInWord(typedWord.charAt(2))) {
                        btnRow1Num3.setBackground(inWord);
                        if (game.checkLetterInPosition(typedWord.charAt(2), game.getMysteryWord().charAt(2))) {
                            btnRow1Num3.setBackground(correct);
                        }
                    } else {
                        if (!txaDiscardedLetters.getText().contains("" + typedWord.charAt(2))) {
                            txaDiscardedLetters.append(typedWord.charAt(2) + " ");
                        }
                    }
                    btnRow1Num4.setText("" + typedWord.charAt(3));
                    if (game.checkLetterInWord(typedWord.charAt(3))) {
                        btnRow1Num4.setBackground(inWord);
                        if (game.checkLetterInPosition(typedWord.charAt(3), game.getMysteryWord().charAt(3))) {
                            btnRow1Num4.setBackground(correct);
                        }
                    } else {
                        if (!txaDiscardedLetters.getText().contains("" + typedWord.charAt(3))) {
                            txaDiscardedLetters.append(typedWord.charAt(3) + " ");
                        }
                    }
                    rows++;
                    break;
                case 2:
                    btnRow2Num1.setText("" + typedWord.charAt(0));
                    if (game.checkLetterInWord(typedWord.charAt(0))) {
                        btnRow2Num1.setBackground(inWord);
                        if (game.checkLetterInPosition(typedWord.charAt(0), game.getMysteryWord().charAt(0))) {
                            btnRow2Num1.setBackground(correct);
                        }
                    } else {
                        if (!txaDiscardedLetters.getText().contains("" + typedWord.charAt(0))) {
                            txaDiscardedLetters.append(typedWord.charAt(0) + " ");
                        }
                    }
                    btnRow2Num2.setText("" + typedWord.charAt(1));
                    if (game.checkLetterInWord(typedWord.charAt(1))) {
                        btnRow2Num2.setBackground(inWord);
                        if (game.checkLetterInPosition(typedWord.charAt(1), game.getMysteryWord().charAt(1))) {
                            btnRow2Num2.setBackground(correct);
                        }
                    } else {
                        if (!txaDiscardedLetters.getText().contains("" + typedWord.charAt(1))) {
                            txaDiscardedLetters.append(typedWord.charAt(1) + " ");
                        }
                    }
                    btnRow2Num3.setText("" + typedWord.charAt(2));
                    if (game.checkLetterInWord(typedWord.charAt(2))) {
                        btnRow2Num3.setBackground(inWord);
                        if (game.checkLetterInPosition(typedWord.charAt(2), game.getMysteryWord().charAt(2))) {
                            btnRow2Num3.setBackground(correct);
                        }
                    } else {
                        if (!txaDiscardedLetters.getText().contains("" + typedWord.charAt(2))) {
                            txaDiscardedLetters.append(typedWord.charAt(2) + " ");
                        }
                    }
                    btnRow2Num4.setText("" + typedWord.charAt(3));
                    if (game.checkLetterInWord(typedWord.charAt(3))) {
                        btnRow2Num4.setBackground(inWord);
                        if (game.checkLetterInPosition(typedWord.charAt(3), game.getMysteryWord().charAt(3))) {
                            btnRow2Num4.setBackground(correct);
                        }
                    } else {
                        if (!txaDiscardedLetters.getText().contains("" + typedWord.charAt(3))) {
                            txaDiscardedLetters.append(typedWord.charAt(3) + " ");
                        }
                    }
                    rows++;
                    break;

                case 3:
                    btnRow3Num1.setText("" + typedWord.charAt(0));
                    if (game.checkLetterInWord(typedWord.charAt(0))) {
                        btnRow3Num1.setBackground(inWord);
                        if (game.checkLetterInPosition(typedWord.charAt(0), game.getMysteryWord().charAt(0))) {
                            btnRow3Num1.setBackground(correct);
                        }
                    } else {
                        if (!txaDiscardedLetters.getText().contains("" + typedWord.charAt(0))) {
                            txaDiscardedLetters.append(typedWord.charAt(0) + " ");
                        }
                    }
                    btnRow3Num2.setText("" + typedWord.charAt(1));
                    if (game.checkLetterInWord(typedWord.charAt(1))) {
                        btnRow3Num2.setBackground(inWord);
                        if (game.checkLetterInPosition(typedWord.charAt(1), game.getMysteryWord().charAt(1))) {
                            btnRow3Num2.setBackground(correct);
                        }
                    } else {
                        if (!txaDiscardedLetters.getText().contains("" + typedWord.charAt(1))) {
                            txaDiscardedLetters.append(typedWord.charAt(1) + " ");
                        }
                    }
                    btnRow3Num3.setText("" + typedWord.charAt(2));
                    if (game.checkLetterInWord(typedWord.charAt(2))) {
                        btnRow3Num3.setBackground(inWord);
                        if (game.checkLetterInPosition(typedWord.charAt(2), game.getMysteryWord().charAt(2))) {
                            btnRow3Num3.setBackground(correct);
                        }
                    } else {
                        if (!txaDiscardedLetters.getText().contains("" + typedWord.charAt(2))) {
                            txaDiscardedLetters.append(typedWord.charAt(2) + " ");
                        }
                    }
                    btnRow3Num4.setText("" + typedWord.charAt(3));
                    if (game.checkLetterInWord(typedWord.charAt(3))) {
                        btnRow3Num4.setBackground(inWord);
                        if (game.checkLetterInPosition(typedWord.charAt(3), game.getMysteryWord().charAt(3))) {
                            btnRow3Num4.setBackground(correct);
                        }
                    } else {
                        if (!txaDiscardedLetters.getText().contains("" + typedWord.charAt(3))) {
                            txaDiscardedLetters.append(typedWord.charAt(3) + " ");
                        }
                    }
                    rows++;
                    break;

                case 4:
                    btnRow4Num1.setText("" + typedWord.charAt(0));
                    if (game.checkLetterInWord(typedWord.charAt(0))) {
                        btnRow4Num1.setBackground(inWord);
                        if (game.checkLetterInPosition(typedWord.charAt(0), game.getMysteryWord().charAt(0))) {
                            btnRow4Num1.setBackground(correct);
                        }
                    } else {
                        if (!txaDiscardedLetters.getText().contains("" + typedWord.charAt(0))) {
                            txaDiscardedLetters.append(typedWord.charAt(0) + " ");
                        }
                    }
                    btnRow4Num2.setText("" + typedWord.charAt(1));
                    if (game.checkLetterInWord(typedWord.charAt(1))) {
                        btnRow4Num2.setBackground(inWord);
                        if (game.checkLetterInPosition(typedWord.charAt(1), game.getMysteryWord().charAt(1))) {
                            btnRow4Num2.setBackground(correct);
                        }
                    } else {
                        if (!txaDiscardedLetters.getText().contains("" + typedWord.charAt(1))) {
                            txaDiscardedLetters.append(typedWord.charAt(1) + " ");
                        }
                    }
                    btnRow4Num3.setText("" + typedWord.charAt(2));
                    if (game.checkLetterInWord(typedWord.charAt(2))) {
                        btnRow4Num3.setBackground(inWord);
                        if (game.checkLetterInPosition(typedWord.charAt(2), game.getMysteryWord().charAt(2))) {
                            btnRow4Num3.setBackground(correct);
                        }
                    } else {
                        if (!txaDiscardedLetters.getText().contains("" + typedWord.charAt(2))) {
                            txaDiscardedLetters.append(typedWord.charAt(2) + " ");
                        }
                    }
                    btnRow4Num4.setText("" + typedWord.charAt(3));
                    if (game.checkLetterInWord(typedWord.charAt(3))) {
                        btnRow4Num4.setBackground(inWord);
                        if (game.checkLetterInPosition(typedWord.charAt(3), game.getMysteryWord().charAt(3))) {
                            btnRow4Num4.setBackground(correct);
                        }
                    } else {
                        if (!txaDiscardedLetters.getText().contains("" + typedWord.charAt(3))) {
                            txaDiscardedLetters.append(typedWord.charAt(3) + " ");
                        }
                    }
                    rows++;
                    break;

                case 5:
                    btnRow5Num1.setText("" + typedWord.charAt(0));
                    if (game.checkLetterInWord(typedWord.charAt(0))) {
                        btnRow5Num1.setBackground(inWord);
                        if (game.checkLetterInPosition(typedWord.charAt(0), game.getMysteryWord().charAt(0))) {
                            btnRow5Num1.setBackground(correct);
                        }
                    } else {
                        if (!txaDiscardedLetters.getText().contains("" + typedWord.charAt(0))) {
                            txaDiscardedLetters.append(typedWord.charAt(0) + " ");
                        }
                    }
                    btnRow5Num2.setText("" + typedWord.charAt(1));
                    if (game.checkLetterInWord(typedWord.charAt(1))) {
                        btnRow5Num2.setBackground(inWord);
                        if (!game.checkLetterInPosition(typedWord.charAt(1), game.getMysteryWord().charAt(1))) {
                            btnRow5Num2.setBackground(correct);
                        }
                    } else {
                        if (!txaDiscardedLetters.getText().contains("" + typedWord.charAt(1))) {
                            txaDiscardedLetters.append(typedWord.charAt(1) + " ");
                        }
                    }
                    btnRow5Num3.setText("" + typedWord.charAt(2));
                    if (game.checkLetterInWord(typedWord.charAt(2))) {
                        btnRow5Num3.setBackground(inWord);
                        if (game.checkLetterInPosition(typedWord.charAt(2), game.getMysteryWord().charAt(2))) {
                            btnRow5Num3.setBackground(correct);
                        }
                    } else {
                        if (!txaDiscardedLetters.getText().contains("" + typedWord.charAt(2))) {
                            txaDiscardedLetters.append(typedWord.charAt(2) + " ");
                        }
                    }
                    btnRow5Num4.setText("" + typedWord.charAt(3));
                    if (game.checkLetterInWord(typedWord.charAt(3))) {
                        btnRow5Num4.setBackground(inWord);
                        if (game.checkLetterInPosition(typedWord.charAt(3), game.getMysteryWord().charAt(3))) {
                            btnRow5Num4.setBackground(correct);
                        }
                    } else {

                        if (!txaDiscardedLetters.getText().contains("" + typedWord.charAt(3))) {
                            txaDiscardedLetters.append(typedWord.charAt(3) + " ");
                        }
                    }

                    rows++;
                    break;
            }
            if (game.getMysteryWord().equals(typedWord)) {
                btnEnterWord.setEnabled(false);
                newUser.setHighScoreGuess(rows - 1); // no. of rows used = num of guesses made

                newUser.setGamesPlayed();
                newUser.setCorrectWords();
                if(skip){
                result = db.update("SET gamesPlayed = " + newUser.getGamesPlayed() + ", "
                        + "correctWords = " + newUser.getCorrectWords() + ", "
                        + "highScoreGuess = " + newUser.getHighScoreGuess() + " "
                        + "WHERE username = " + newUser.getUsername() + " WHERE username = '" + newUser.getUsername()+"';");
                }
                // 6 because although there are 5 rows, the switch-case increments the value by 1 upon exit
                    game.setNumOfGuesses(rows - 1); // no. of rows used = num of guesses made
                
                
                int choice = JOptionPane.showConfirmDialog(this, "You have won! You guessed the word '" + game.getMysteryWord() + "' correctly."
                        + "\nDo you want to play again?", "YAY!", JOptionPane.YES_NO_OPTION);
                if (choice == 0) {
                    frmUserPage.setVisible(true);
                    this.setVisible(false);
                } else {
                    System.exit(0);
                }
            } 
            else if(rows == 6){

                int choice = JOptionPane.showConfirmDialog(this, "You have Lost! You guessed the word '" + game.getMysteryWord() + "' incorrectly."
                        + "\nDo you want to play again?", "SHAME!", JOptionPane.YES_NO_OPTION);
                if (choice == 0) {
                    frmUserPage.setVisible(true);
                    this.setVisible(false);
                } else {
                    System.exit(0);
                }
            } 
            
            txfWordField.setText(""); // remove text after submitting word
        } else {
            btnEnterWord.setEnabled(false);
            JOptionPane.showMessageDialog(this, "Please Enter Valid 4-letter word", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }

    public void enterButton() {
        String password = passPassword.getText();
        String username = txfUsername.getText();
        boolean taken = true;
        if ((txfUsername.getText().isEmpty()) || (passPassword.getText().isEmpty())
                || !(radLogin.isSelected() || radSignup.isSelected())) {
            JOptionPane.showMessageDialog(this, "Please Fill out whole form", "Error", JOptionPane.ERROR_MESSAGE);
            btnEnterUserInfo.setEnabled(false);
        } else {

            if (radSignup.isSelected()) {
                if (password.length() > 8) {
                    newUser.setPassword(password);
                    newUser.setUsername(username);

                    String sql = "SELECT * FROM userInformation;";
                    System.out.println(sql);
                    ResultSet rs = db.query(sql);
                    int check = 0;
                    try {
                        while (rs.next() && check == 0) {
                            String user = rs.getString("username");
                            System.out.println(user);

                            if (newUser.getUsername().equalsIgnoreCase(user)) {
                                JOptionPane.showMessageDialog(null, "Username Taken", "Error", JOptionPane.ERROR_MESSAGE);
                                check++;
                                taken = false;

                            } else {

                                taken = true;

                            }
                        }

                        if (taken) {
                            result = db.update("INSERT INTO userInformation(username, password) VALUES (\"" + newUser.getUsername() + "\", \"" + newUser.getPassword() + "\")");
                            System.out.println(result);
                            check++;

                            frmLogin.setVisible(false);
                            frmUserPage.setVisible(true);
                            txaInfoArea.setText("Username:" + newUser.getUsername()
                                    + "\nPassword: " + newUser.getPassword()
                                    + "\nGames Played: " + newUser.getGamesPlayed()
                                    + "\nNumber of Correct Words Guessed: " + newUser.getCorrectWords()
                                    + "\nLeast Guesses for a Word: " + newUser.getHighScoreGuess());
                        }
                    } catch (SQLException ex) {

                        System.out.println("error");
                        Logger.getLogger(SQLinterface.class.getName()).log(Level.SEVERE, null, ex);
                    }
//                if(a.getResult() == 1){
//                    
//                    frmLogin.setEnabled(false);
//                    frmUserPage.setEnabled(true);
//                    txaInfoArea.setText("Username:" + newUser.getUsername()
//                    + "\nPassword: " + newUser.getPassword()
//                    + "\nGames Played: " + newUser.getGamesPlayed()
//                    + "\nNumber of Correct Words Guessed: " + newUser.getCorrectWords()
//                    + "\nLeast Guesses for a Word: " + newUser.getHighScoreGuess());
//                    
//                    
//                }
                } else {
                    JOptionPane.showMessageDialog(this, "Password not long enough. Min of 9 characters long", "Error", JOptionPane.ERROR_MESSAGE);
                    btnEnterUserInfo.setEnabled(false);

                }
            } else if (radLogin.isSelected()) {
                // SQLinterface b = new SQLinterface(newUser,"SELECT username, password FROM userInformation;",'b');

                boolean found = false;
                String sql = "SELECT * FROM userInformation WHERE username = " + newUser.getUsername() + " AND password =" + newUser.getPassword() + ";";
                ResultSet rs = db.query(sql);
           //     int check = 0;

                try {
                    if(rs.next()) {
                        String user = rs.getString("username");
                        System.out.println(user);
                        //if (newUser.getUsername().equals(user)) {
                            String passwrd = rs.getString("password");
                            
                          //  if (newUser.getPassword().equals(passwrd)) {
                            //    check++;
//                                newUser.setUsername(user);
//                                newUser.setPassword(passwrd);
  
                                found = true;

//                            } else {
//                                JOptionPane.showMessageDialog(null, "Incorrect Password", "Error", JOptionPane.ERROR_MESSAGE);
//                                found = false;
//                            }
//                        } else {
//                            JOptionPane.showMessageDialog(null, "Username not found", "Error", JOptionPane.ERROR_MESSAGE);
//                            found = false;
//                        }

                    }
                    
                       if (found) {
                    frmLogin.setVisible(false);
                    frmUserPage.setVisible(true);

                    txaInfoArea.setText("Username:" + newUser.getUsername()
                            + "\nPassword: " + newUser.getPassword()
                            + "\nGames Played: " + newUser.getGamesPlayed()
                            + "\nNumber of Correct Words Guessed: " + newUser.getCorrectWords()
                            + "\nLeast Guesses for a Word: " + newUser.getHighScoreGuess());
                }else{
                       JOptionPane.showMessageDialog(null, "Username not found", "Error", JOptionPane.ERROR_MESSAGE);
                       }
                } catch (SQLException ex) {
                    System.out.println("error");
                    Logger.getLogger(SQLinterface.class.getName()).log(Level.SEVERE, null, ex);
                }

            }

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceDesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceDesign().setVisible(false);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToLogin;
    private javax.swing.JButton btnEnterUserInfo;
    private javax.swing.JButton btnEnterWord;
    private javax.swing.JButton btnGuest;
    private javax.swing.JButton btnPlay;
    private javax.swing.JButton btnRow1Num1;
    private javax.swing.JButton btnRow1Num2;
    private javax.swing.JButton btnRow1Num3;
    private javax.swing.JButton btnRow1Num4;
    private javax.swing.JButton btnRow2Num1;
    private javax.swing.JButton btnRow2Num2;
    private javax.swing.JButton btnRow2Num3;
    private javax.swing.JButton btnRow2Num4;
    private javax.swing.JButton btnRow3Num1;
    private javax.swing.JButton btnRow3Num2;
    private javax.swing.JButton btnRow3Num3;
    private javax.swing.JButton btnRow3Num4;
    private javax.swing.JButton btnRow4Num1;
    private javax.swing.JButton btnRow4Num2;
    private javax.swing.JButton btnRow4Num3;
    private javax.swing.JButton btnRow4Num4;
    private javax.swing.JButton btnRow5Num1;
    private javax.swing.JButton btnRow5Num2;
    private javax.swing.JButton btnRow5Num3;
    private javax.swing.JButton btnRow5Num4;
    private javax.swing.JButton btnRules;
    private javax.swing.JFrame frmLogin;
    private javax.swing.JFrame frmUserPage;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblBanner;
    private javax.swing.JLabel lblDiscardedLetters;
    private javax.swing.JLabel lblFifth;
    private javax.swing.JLabel lblFirst;
    private javax.swing.JLabel lblFourth;
    private javax.swing.JLabel lblLeaderboard;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblSecond;
    private javax.swing.JLabel lblThird;
    private javax.swing.JLabel lblUserInformation;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLayeredPane lpaneBackground;
    private javax.swing.JPasswordField passPassword;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlLeaderboard;
    private javax.swing.JRadioButton radLogin;
    private javax.swing.JRadioButton radSignup;
    private javax.swing.ButtonGroup rgpAccount;
    private javax.swing.JScrollPane scrllPanelDiscardment;
    private javax.swing.JTextArea txaDiscardedLetters;
    private javax.swing.JTextArea txaInfoArea;
    private javax.swing.JTextField txfUsername;
    private javax.swing.JTextField txfWordField;
    // End of variables declaration//GEN-END:variables
}
